ALTER TABLE `uni1_users` ADD `achievements_mine` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_research` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_battle` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_ship` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_defence` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_storage` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_moon` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_colony` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_friend` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_statpoints` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_destroy` INT( 11 ) NOT NULL DEFAULT '1',
ADD `achievements_debris` INT( 11 ) NOT NULL DEFAULT '1'
